# Menu
menu:
  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
  Tag: /tags
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: Read More...

# MIIT ICP/IP/DOMAIN
beian:
  enable: true
  number: 鲁ICP备2021004995号-1
  url: https://beian.miit.gov.cn/

# Tags
show_count: true

# Toc
toc: true

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: true # true
  clientID: 7f7ce31516ded730be17 # GitHub Application Client ID
  clientSecret: 90b34057e4efaa58489586c7a99e6b05c62c6a5a # Client Secret
  repo: blog # Repository name
  owner: niuyi1017 # GitHub ID
  admin: niuyi1017 # GitHub ID

# Valine
valine:
  enable: false # true
  el: "vcomments"
  appId:
  appKey:
  notify: false
  verify: true
  avatar: "mp"
  pageSize: "10"
  placeholder: "请输入..."
